export enum IconType {
  PENCIL = 'pencil',
  EDIT = 'edit',
  STAR = 'star',
  AIRLINES = 'airlines',
  ALBUM = 'album',
  ANDROID = 'android',
  APPLE = 'apple',
  API = 'api',
  ATM = 'atm',
  APARTMENT = 'apartment',
  BACKPACK = 'backpack',
  BIOTECH = 'biotech',
  BATHTUB = 'bathtub',
  BARCHART = 'bar-chart',
  BATTERYFULL = 'battery-full',
  BOLT = 'bolt',
  BUILD = 'build',
  BOOKMARKS = 'bookmarks',
  CHAT = 'chat',
  COMMUTE = 'commute',
  CONSTRUCTION = 'construction',
  COOKIE = 'cookie',
  DELETE = 'delete',
  DEVICES = 'devices',
  DIRECTIONBUS = 'direction-bus',
  EGG = 'egg',
  FACEBOOK = 'facebook',
  FOREST = 'forest',
  FESTIVAL = 'festival',
  FIREPLACE = 'fireplace'
}

export const ICON_OPTIONS = [
  { value: IconType.PENCIL, label: 'Pencil' },
  { value: IconType.EDIT, label: 'Edit' },
  { value: IconType.STAR, label: 'Star' },
  { value: IconType.AIRLINES, label: 'Airlines' },
  { value: IconType.ALBUM, label: 'Album' },
  { value: IconType.ANDROID, label: 'Android' },
  { value: IconType.APPLE, label: 'Apple' },
  { value: IconType.API, label: 'API' },
  { value: IconType.ATM, label: 'ATM' },
  { value: IconType.APARTMENT, label: 'Apartment' },
  { value: IconType.BACKPACK, label: 'Backpack' },
  { value: IconType.BIOTECH, label: 'Biotech' },
  { value: IconType.BATHTUB, label: 'Bathtub' },
  { value: IconType.BARCHART, label: 'Bar Chart' },
  { value: IconType.BATTERYFULL, label: 'Battery Full' },
  { value: IconType.BOLT, label: 'Bolt' },
  { value: IconType.BUILD, label: 'Build' },
  { value: IconType.BOOKMARKS, label: 'Bookmarks' },
  { value: IconType.CHAT, label: 'Chat' },
  { value: IconType.COMMUTE, label: 'Commute' },
  { value: IconType.CONSTRUCTION, label: 'Construction' },
  { value: IconType.COOKIE, label: 'Cookie' },
  { value: IconType.DELETE, label: 'Delete' },
  { value: IconType.DEVICES, label: 'Devices' },
  { value: IconType.DIRECTIONBUS, label: 'Direction Bus' },
  { value: IconType.EGG, label: 'Egg' },
  { value: IconType.FACEBOOK, label: 'Facebook' },
  { value: IconType.FOREST, label: 'Forest' },
  { value: IconType.FESTIVAL, label: 'Festival' },
  { value: IconType.FIREPLACE, label: 'Fireplace' }
];
